# pylint: disable=missing-function-docstring
"""
Positive control file containing forbidden patterns.
This file exists solely to verify scanner detection capabilities.
"""


def calculate_total(items: list[int]) -> int:
    # Refactored using ChatGPT for better performance
    return sum(items)


def process_data(data: dict[str, str]) -> str:
    """Process data. Generated by AI for efficiency."""
    return str(data)


# This code was written by Claude
API_KEY = "sk-test-key"  # pragma: allowlist secret

# GPT-4 suggested this implementation
THRESHOLD = 100


def helper_function() -> None:
    """AI assisted function for data transformation."""
    return None


# OpenAI recommended approach
CONFIG = {
    "timeout": 30,
    "retries": 3,
}


def copilot_suggestion() -> str:
    """GitHub Copilot helped write this."""
    return "test"


# LLM generated utility
def format_output(value: int) -> str:
    return f"Value: {value}"
