name: Tech Debt
description: Document technical debt requiring attention
labels: ["type: debt", "status: triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Backend
        - Frontend
        - Infrastructure
        - Data Pipeline
    validations:
      required: true

  - type: textarea
    id: cost-of-delay
    attributes:
      label: Cost of Delay
      description: What happens if we don't address this? What is the compounding cost?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Rough engineering plan to address this debt
    validations:
      required: true

  - type: dropdown
    id: effort-estimate
    attributes:
      label: Effort Estimate
      description: Approximate effort required
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (> 3 days)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
