name: 'techpulse'
version: '1.0.0'

profile: 'techpulse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  techpulse:
    tech_taxonomy:
      +column_types:
        tech_key: varchar
        display_name: varchar
        category: varchar
        regex_pattern: varchar
